export const ALL_PRODUCT_REQUEST = ALL_PRODUCT_REQUEST;
export const ALL_PRODUCT_SUCCESS = ALL_PRODUCT_SUCCESS;
export const ALL_PRODUCT_FAILED = ALL_PRODUCT_FAILED;
export const CLEAR_ERROR = CLEAR_ERROR;
